# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
import recommonmark
from recommonmark.transform import AutoStructify

# -- Project information -----------------------------------------------------

project = 'helloSystem'
copyright = '2020, probono'
author = 'probono'

# The full version, including alpha/beta/rc tags
release = 'pre-alpha'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    # Auto-generate section labels.
    'sphinx.ext.autosectionlabel',
    'recommonmark'
]

master_doc = 'index'

# Prefix document path to section labels, otherwise autogenerated labels would look like 'heading'
# rather than 'path/to/file:heading'
autosectionlabel_prefix_document = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'README.md']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Display "Edit on GitHub"
import os
html_context = {
  'display_github': True,
  'github_user': os.environ['GITHUB_REPOSITORY'].split("/")[0],
  'github_repo': os.environ['GITHUB_REPOSITORY'].split("/")[1],
  'github_version': 'main/',
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

github_doc_root = 'https://github.com/' + os.environ['GITHUB_REPOSITORY'] + '/tree/main/'

# autodoc configuration with AutoStructify
# https://github.com/symuvia/symupy/issues/37#issuecomment-678322450
# See http://recommonmark.readthedocs.io/en/latest/auto_structify.html
# See the setup function in current conf.py file in the recommonmark repo
# https://github.com/rtfd/recommonmark/blob/master/docs/conf.py#L296
github_doc_root = 'https://github.com/helloSystem/docs/tree/main/'

# We can't rely on anchors because GitHub dynamically renders them for
# markdown documents.
linkcheck_anchors = False

def setup(app):
    app.add_config_value('recommonmark_config', {
        'url_resolver': lambda url: github_doc_root + url,
        'auto_toc_tree_section': 'Contents',
        'enable_eval_rst': True,
        'enable_auto_doc_ref': False,
    }, True)
    app.add_transform(AutoStructify)
