---
name: CI

on:
  push:
    branches: [main]
    tags-ignore:
      - 'continuous'
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      G_TOKEN: ${{secrets.GITHUB_TOKEN}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Build docs
        run: sudo -E bash -ex buildDocs.sh
      - name: Deploy EPUB (only when building from main branch)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
          bash ./upload.sh _build/epub/*.epub
